### ISSUE TITLE
세션 내부 페이지 구현

### ISSUE THREAD

**Issue by MONOTYPEEE** [MONOTYPEEE/PlayHere#15]
# TO-DO
- [x] 데이터 동기화 로직
- [x] YouTube 검색 & 대기열 추가
- [x] 재생 상태 컨트롤
- [x] 호스트/게스트 구분 로직
